/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConsentRouteImport } from './routes/consent'
import { Route as HubRouteImport } from './routes/hub'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as ModeRouteImport } from './routes/mode'
import { Route as OnsetRouteImport } from './routes/onset'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as CheckLetterRouteImport } from './routes/check.$letter'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsentRoute = ConsentRouteImport.update({
  id: '/consent',
  path: '/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const HubRoute = HubRouteImport.update({
  id: '/hub',
  path: '/hub',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const ModeRoute = ModeRouteImport.update({
  id: '/mode',
  path: '/mode',
  getParentRoute: () => rootRouteImport,
} as any)
const OnsetRoute = OnsetRouteImport.update({
  id: '/onset',
  path: '/onset',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckLetterRoute = CheckLetterRouteImport.update({
  id: '/check/$letter',
  path: '/check/$letter',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/consent': typeof ConsentRoute
  '/hub': typeof HubRoute
  '/learn': typeof LearnRoute
  '/mode': typeof ModeRoute
  '/onset': typeof OnsetRoute
  '/results': typeof ResultsRoute
  '/check/$letter': typeof CheckLetterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/consent': typeof ConsentRoute
  '/hub': typeof HubRoute
  '/learn': typeof LearnRoute
  '/mode': typeof ModeRoute
  '/onset': typeof OnsetRoute
  '/results': typeof ResultsRoute
  '/check/$letter': typeof CheckLetterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/consent': typeof ConsentRoute
  '/hub': typeof HubRoute
  '/learn': typeof LearnRoute
  '/mode': typeof ModeRoute
  '/onset': typeof OnsetRoute
  '/results': typeof ResultsRoute
  '/check/$letter': typeof CheckLetterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/consent'
    | '/hub'
    | '/learn'
    | '/mode'
    | '/onset'
    | '/results'
    | '/check/$letter'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/consent'
    | '/hub'
    | '/learn'
    | '/mode'
    | '/onset'
    | '/results'
    | '/check/$letter'
  id:
    | '__root__'
    | '/'
    | '/consent'
    | '/hub'
    | '/learn'
    | '/mode'
    | '/onset'
    | '/results'
    | '/check/$letter'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConsentRoute: typeof ConsentRoute
  HubRoute: typeof HubRoute
  LearnRoute: typeof LearnRoute
  ModeRoute: typeof ModeRoute
  OnsetRoute: typeof OnsetRoute
  ResultsRoute: typeof ResultsRoute
  CheckLetterRoute: typeof CheckLetterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consent': {
      id: '/consent'
      path: '/consent'
      fullPath: '/consent'
      preLoaderRoute: typeof ConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub': {
      id: '/hub'
      path: '/hub'
      fullPath: '/hub'
      preLoaderRoute: typeof HubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mode': {
      id: '/mode'
      path: '/mode'
      fullPath: '/mode'
      preLoaderRoute: typeof ModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onset': {
      id: '/onset'
      path: '/onset'
      fullPath: '/onset'
      preLoaderRoute: typeof OnsetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check/$letter': {
      id: '/check/$letter'
      path: '/check/$letter'
      fullPath: '/check/$letter'
      preLoaderRoute: typeof CheckLetterRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConsentRoute: ConsentRoute,
  HubRoute: HubRoute,
  LearnRoute: LearnRoute,
  ModeRoute: ModeRoute,
  OnsetRoute: OnsetRoute,
  ResultsRoute: ResultsRoute,
  CheckLetterRoute: CheckLetterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
